import type { Locale } from "./types";

const copy = {
  en: {
    demoMode: "Synthetic demo",
    localOnly: "Local only",
    connected: "API connected",
    disconnected: "API unavailable",
    cases: "Inspection cases",
    newCase: "New case",
    loadDemo: "Load deterministic demo",
    partId: "Part ID",
    revision: "Revision",
    create: "Create case",
    emptyCases: "No inspection cases yet.",
    workspace: "Inspection workspace",
    reference: "Reference",
    inspection: "Inspection",
    overlay: "Anomaly overlay",
    run: "Run baseline inspection",
    rerun: "Run again",
    uploadReference: "Upload reference",
    uploadInspection: "Upload inspection",
    evidence: "Evidence integrity",
    evidenceHint: "Every result is bound to identity, revision, inputs, and reviewer action.",
    ready: "Ready",
    missing: "Missing",
    anomalyScore: "Anomaly score",
    threshold: "Threshold",
    affectedFeature: "Affected feature",
    pipeline: "Pipeline",
    modelVerdict: "Model verdict",
    noAnalysis: "Run inspection to create deterministic evidence.",
    disposition: "Human disposition",
    dispositionHint: "The model proposes evidence. A reviewer owns the decision.",
    reviewer: "Reviewer",
    note: "Decision note",
    accept: "Accept",
    reject: "Reject",
    needsReview: "Needs review",
    modelError: "Model error",
    record: "Record disposition",
    export: "Export verified bundle",
    exporting: "Exporting…",
    limitations: "Demo boundary",
    limitationText: "Synthetic evidence only. Not validated for production, safety, or shop-floor release.",
    caseIdentity: "Part + revision identity",
    caseRevision: "Case state revision",
    referenceHash: "Reference image hash",
    inputHash: "Inspection image hash",
    configHash: "Configuration hash",
    maskHash: "Anomaly mask hash",
    reviewRecord: "Human review record",
    openCase: "Open inspection case",
    language: "Language",
    processing: "Processing…",
    safeFailure: "The operation stopped safely",
    selectCase: "Select or create a case to begin.",
    captured: "Evidence bundle verified",
    normalizedDifference: "Normalized pixel difference",
    unmapped: "Unmapped",
    notApplicable: "No anomaly to map",
  },
  ko: {
    demoMode: "합성 데이터 데모",
    localOnly: "로컬 전용",
    connected: "API 연결됨",
    disconnected: "API 연결 안 됨",
    cases: "검사 케이스",
    newCase: "새 케이스",
    loadDemo: "결정론적 데모 불러오기",
    partId: "부품 ID",
    revision: "리비전",
    create: "케이스 생성",
    emptyCases: "아직 검사 케이스가 없습니다.",
    workspace: "검사 워크스페이스",
    reference: "정상 기준",
    inspection: "검사 이미지",
    overlay: "이상 영역 표시",
    run: "기준 검사 실행",
    rerun: "다시 실행",
    uploadReference: "기준 이미지 업로드",
    uploadInspection: "검사 이미지 업로드",
    evidence: "증거 무결성",
    evidenceHint: "모든 결과를 부품, 리비전, 입력 해시, 사람 판정에 연결합니다.",
    ready: "준비됨",
    missing: "누락",
    anomalyScore: "이상 점수",
    threshold: "판정 임계값",
    affectedFeature: "영향받은 피처",
    pipeline: "검사 파이프라인",
    modelVerdict: "모델 판정",
    noAnalysis: "검사를 실행해 결정론적 증거를 생성하세요.",
    disposition: "사람 최종 판정",
    dispositionHint: "모델은 증거를 제안하고, 최종 판단은 검토자가 소유합니다.",
    reviewer: "검토자",
    note: "판정 메모",
    accept: "승인",
    reject: "반려",
    needsReview: "추가 검토",
    modelError: "모델 오류",
    record: "판정 기록",
    export: "검증된 번들 내보내기",
    exporting: "내보내는 중…",
    limitations: "데모 적용 범위",
    limitationText: "합성 증거 전용입니다. 생산, 안전, 작업장 출하 검증을 주장하지 않습니다.",
    caseIdentity: "부품 + 리비전 식별",
    caseRevision: "케이스 상태 리비전",
    referenceHash: "기준 이미지 해시",
    inputHash: "검사 이미지 해시",
    configHash: "설정 해시",
    maskHash: "이상 마스크 해시",
    reviewRecord: "사람 검토 기록",
    openCase: "검사 케이스 열기",
    language: "언어",
    processing: "처리 중…",
    safeFailure: "작업이 안전하게 중단되었습니다",
    selectCase: "케이스를 선택하거나 새로 만드세요.",
    captured: "증거 번들 검증 완료",
    normalizedDifference: "정규화 픽셀 차이",
    unmapped: "매핑되지 않음",
    notApplicable: "매핑할 이상 없음",
  },
} as const;

export type Copy = (typeof copy)["en"];

export function getCopy(locale: Locale): Copy {
  return copy[locale] as Copy;
}
