import type { Locale } from "./types";

const copy = {
  en: {
    productKicker: "Industrial evidence workbench",
    demoMode: "Synthetic demo",
    localOnly: "Local only",
    connected: "API connected",
    disconnected: "API unavailable",
    cases: "Inspection cases",
    caseRegistry: "Case registry",
    caseLabel: "Case",
    stateRevision: "State rev",
    casesCount: "inspection cases",
    newCase: "New case",
    loadDemo: "Load deterministic demo",
    partId: "Part ID",
    revision: "Revision",
    create: "Create case",
    emptyCases: "No inspection cases yet.",
    surfaceNavigation: "Workbench views",
    inspectionTab: "Inspection",
    evaluationTab: "E1 Evaluation",
    workspace: "Inspection workspace",
    reference: "Reference",
    inspection: "Inspection",
    imageComparison: "Image comparison",
    inspectionMetrics: "Inspection metrics",
    bindingMissing: "Inspection evidence binding is missing. Result display stopped.",
    noReferenceEvidence: "No reference image registered",
    noInspectionEvidence: "No inspection image registered",
    overlay: "Anomaly overlay",
    run: "Run baseline inspection",
    rerun: "Run again",
    uploadReference: "Upload reference",
    uploadInspection: "Upload inspection",
    evidence: "Evidence integrity",
    lineage: "Lineage",
    evidenceHint: "Every result is bound to identity, revision, inputs, and reviewer action.",
    ready: "Ready",
    missing: "Missing",
    anomalyScore: "Anomaly score",
    maskArea: "Mask area of image pixels",
    maskLocation: "Mask location",
    threshold: "Threshold",
    affectedFeature: "Affected feature",
    pipeline: "Pipeline",
    modelVerdict: "Model verdict",
    noAnalysis: "Run inspection to create deterministic evidence.",
    disposition: "Human disposition",
    humanLoop: "Human-in-the-loop",
    dispositionHint: "The model proposes evidence. A reviewer owns the decision.",
    reviewer: "Reviewer",
    defaultReviewer: "Local Reviewer",
    note: "Decision note",
    notePlaceholder: "Evidence reviewed; disposition rationale…",
    accept: "Accept",
    reject: "Reject",
    needsReview: "Needs review",
    modelError: "Model error",
    record: "Record disposition",
    export: "Export verified bundle",
    exporting: "Exporting…",
    limitations: "Demo boundary",
    limitationText: "Synthetic evidence only. Not validated for production, safety, or shop-floor release.",
    caseIdentity: "Part + revision identity",
    caseRevision: "Case state revision",
    referenceHash: "Reference image hash",
    inputHash: "Inspection image hash",
    configHash: "Configuration hash",
    maskHash: "Anomaly mask hash",
    reviewRecord: "Human review record",
    openCase: "Open inspection case",
    language: "Language",
    processing: "Processing…",
    safeFailure: "The operation stopped safely",
    dismissError: "Dismiss error",
    dismissNotice: "Dismiss notice",
    selectCase: "Select or create a case to begin.",
    captured: "Evidence bundle verified",
    normalizedDifference: "Normalized pixel difference",
    unmapped: "Unmapped",
    notApplicable: "No anomaly to map",
    statusDraft: "Draft",
    statusReady: "Ready",
    statusAnalyzed: "Analyzed",
    statusDisposed: "Reviewed",
    statusExported: "Exported",
    statusFailed: "Blocked",
    evaluation: {
      kicker: "Preregistered E1 evidence",
      title: "Synthetic robustness evaluation",
      summary: "A read-only view of the latest frozen E1 result and its release gates.",
      boundaryBadge: "SYNTHETIC ONLY · NOT FIELD_READY",
      boundaryText: "These results characterize deterministic synthetic fixtures only. They do not validate real cameras, parts, operators, safety, or shop-floor release.",
      loadingTitle: "Loading the latest E1 snapshot",
      loadingText: "Reading the frozen result, gate evidence, and bounded gallery from the local API.",
      errorTitle: "Evaluation evidence is unavailable",
      errorText: "No result was accepted for display. Inspection remains available and unchanged.",
      emptyTitle: "No E1 evaluation has been published",
      emptyText: "Generate and validate an E1 artifact outside this read-only interface, then refresh.",
      retry: "Retry read",
      refresh: "Refresh snapshot",
      latestSnapshot: "Latest accepted snapshot",
      verdict: "Release gate verdict",
      passMeaning: "All displayed preregistered gates passed for this synthetic profile.",
      holdMeaning: "One or more preregistered gates blocked this synthetic profile.",
      profileContract: "Dataset profiles",
      activeProfile: "Active",
      selectProfile: "Load evaluation profile",
      miniProfile: "Mini",
      fullProfile: "Full",
      cases: "cases",
      profileCases: "profile cases",
      inferenceCases: "Inference cases",
      trustCases: "Trust-boundary cases",
      runId: "Evaluation run",
      generatedAt: "Generated",
      baseline: "Pinned baseline",
      imageThreshold: "Image threshold",
      thresholdSource: "Threshold source",
      gatesTitle: "PASS / HOLD gates",
      gatesHint: "Thresholds were frozen before held-out test results were read.",
      noGates: "Calibration stopped on HOLD before test gates were evaluated; no synthetic zero values are shown.",
      gatesTable: "E1 acceptance gate results",
      gate: "Gate",
      observed: "Observed",
      required: "Required",
      evidenceCount: "Evidence count",
      status: "Status",
      metricsTitle: "Headline metrics",
      metricsHint: "Every rate keeps its numerator and denominator visible.",
      noMetrics: "Calibration stopped on HOLD before test metrics were evaluated; no synthetic zero values are shown.",
      undefinedMetric: "Undefined for this evaluated slice",
      confusionTitle: "Raw confusion matrix",
      confusionHint: "Held-out image decisions are shown as unrounded TP, TN, FP, and FN counts.",
      confusionTable: "E1 held-out image confusion matrix",
      actualOutcome: "Actual outcome",
      predictedAnomaly: "Predicted anomaly",
      predictedNormal: "Predicted normal",
      actualAnomaly: "Actual anomaly",
      actualNormal: "Actual normal",
      truePositive: "True positive (TP)",
      trueNegative: "True negative (TN)",
      falsePositive: "False positive (FP)",
      falseNegative: "False negative (FN)",
      totalEvaluated: "Total evaluated",
      noConfusion: "No held-out confusion matrix was produced.",
      distributionTitle: "Positive-case Dice / IoU distribution",
      distributionHint: "Every held-out positive case remains visible; the median never replaces case-level evidence.",
      distributionTable: "E1 positive-case Dice and IoU distribution",
      defectType: "Defect type",
      severity: "Severity",
      dice: "Dice",
      iou: "IoU",
      truthPixels: "Truth pixels",
      predictedPixels: "Predicted pixels",
      intersectionPixels: "Intersection",
      showingDistribution: "Showing all",
      positiveCases: "positive cases",
      noDistribution: "No held-out positive-case distribution was produced.",
      slicesTitle: "Evaluation slices",
      slicesHint: "Slice-level evidence prevents an aggregate score from hiding subgroup failures.",
      slicesTable: "E1 metric results by evaluation slice",
      slice: "Slice",
      sampleCount: "Samples",
      metric: "Metric",
      value: "Value",
      noSlices: "No slice metrics were included in this snapshot.",
      trustTitle: "Trust-boundary checks",
      trustHint: "Invalid inputs must return the expected code and publish zero artifacts.",
      trustTable: "E1 trust-boundary results",
      caseId: "Case",
      expectedCode: "Expected code",
      observedCode: "Observed code",
      publishedArtifacts: "Published artifacts",
      noTrustCases: "No trust-boundary cases were included in this snapshot.",
      galleryTitle: "Error explorer",
      galleryHint: "A bounded review sample with side-by-side source, mask, overlay, identity, and hash evidence.",
      showingGallery: "Showing",
      ofGallery: "of",
      galleryItems: "gallery items",
      category: "Failure category",
      part: "Part ID",
      cadRevision: "CAD revision",
      expectedFeature: "Expected feature",
      predictedFeature: "Predicted feature",
      failureReason: "Failure reason",
      notRecorded: "not recorded",
      assetUnavailable: "not published",
      referenceAsset: "Reference",
      inspectionAsset: "Inspection",
      authoritativeMaskAsset: "Authoritative mask",
      predictedMaskAsset: "Predicted mask",
      overlayAsset: "Overlay",
      sourceHashes: "Exact source hashes",
      sourceReferenceHash: "Reference SHA-256",
      sourceInspectionHash: "Inspection SHA-256",
      sourceAuthoritativeMaskHash: "Authoritative mask SHA-256",
      sourcePredictedMaskHash: "Predicted mask SHA-256",
      score: "Score",
      galleryThreshold: "Locked threshold",
      noGallery: "No gallery assets were included in this snapshot.",
      reproductionTitle: "Exact reproduction commands",
      reproductionHint: "Run these commands from the repository root. This interface never executes them.",
      reproductionCommands: "E1 evaluation reproduction commands",
      exclusionsTitle: "Protocol exclusions",
      limitationsTitle: "Scope limitations",
      lineageTitle: "Immutable result bindings",
      protocol: "Protocol",
      dataset: "Dataset",
      datasetHash: "Dataset manifest",
      configurationHash: "Configuration",
      thresholdLock: "Threshold lock",
      resultHash: "Result",
      commit: "Code commit",
      worktree: "Worktree",
      clean: "clean",
      dirty: "dirty — HOLD review required",
      gateLabels: {
        mediumHighDefectRecall: "Medium/high defect recall",
        nuisanceOnlyFalsePositiveRate: "Nuisance-only false-positive rate",
        positiveCaseMedianDice: "Positive-case median Dice",
        affectedFeatureMappingAccuracy: "Affected-feature mapping accuracy",
        revisionMismatchPublicationCount: "Revision mismatch publication count",
        corruptedEvidencePublicationCount: "Corrupted evidence publication count",
        bundleVerifyReimportRate: "Bundle verify/re-import rate",
        datasetSplitHashOverlap: "Dataset split hash overlap",
        sameSeedManifestEquivalence: "Same-seed manifest equivalence",
        v01Regression: "v0.1 regression",
      },
      metricLabels: {
        imagePrecision: "Image precision",
        imageRecall: "Image recall",
        maskPrecision: "Mask precision",
        maskRecall: "Mask recall",
        abstentionCorrectness: "Abstention correctness",
        classificationAccuracy: "Classification accuracy",
      },
      sliceLabels: {
        recallBySeverity: "Recall by severity",
        recallByDefectType: "Recall by defect type",
        nuisanceFalsePositiveRate: "Nuisance false-positive rate",
        classificationByRevision: "Classification by revision",
        classificationByView: "Classification by view",
      },
    },
    footerTarget: "DEMO_READY target · synthetic fixtures",
    footerContract: "Evidence contract v1.0.0",
    footerBoundary: "Not production validated",
  },
  ko: {
    productKicker: "산업 증거 워크벤치",
    demoMode: "합성 데이터 데모",
    localOnly: "로컬 전용",
    connected: "API 연결됨",
    disconnected: "API 연결 안 됨",
    cases: "검사 케이스",
    caseRegistry: "케이스 레지스트리",
    caseLabel: "케이스",
    stateRevision: "상태 리비전",
    casesCount: "개의 검사 케이스",
    newCase: "새 케이스",
    loadDemo: "결정론적 데모 불러오기",
    partId: "부품 ID",
    revision: "리비전",
    create: "케이스 생성",
    emptyCases: "아직 검사 케이스가 없습니다.",
    surfaceNavigation: "워크벤치 보기",
    inspectionTab: "검사",
    evaluationTab: "E1 평가",
    workspace: "검사 워크스페이스",
    reference: "정상 기준",
    inspection: "검사 이미지",
    imageComparison: "이미지 비교",
    inspectionMetrics: "검사 지표",
    bindingMissing: "검사 증거 연결이 누락되어 결과 표시를 중단했습니다.",
    noReferenceEvidence: "등록된 기준 이미지가 없습니다",
    noInspectionEvidence: "등록된 검사 이미지가 없습니다",
    overlay: "이상 영역 표시",
    run: "기준 검사 실행",
    rerun: "다시 실행",
    uploadReference: "기준 이미지 업로드",
    uploadInspection: "검사 이미지 업로드",
    evidence: "증거 무결성",
    lineage: "계보",
    evidenceHint: "모든 결과를 부품, 리비전, 입력 해시, 사람 판정에 연결합니다.",
    ready: "준비됨",
    missing: "누락",
    anomalyScore: "이상 점수",
    maskArea: "이미지 픽셀 대비 마스크 면적",
    maskLocation: "마스크 위치",
    threshold: "판정 임계값",
    affectedFeature: "영향받은 피처",
    pipeline: "검사 파이프라인",
    modelVerdict: "모델 판정",
    noAnalysis: "검사를 실행해 결정론적 증거를 생성하세요.",
    disposition: "사람 최종 판정",
    humanLoop: "사람 검토 포함",
    dispositionHint: "모델은 증거를 제안하고, 최종 판단은 검토자가 소유합니다.",
    reviewer: "검토자",
    defaultReviewer: "로컬 검토자",
    note: "판정 메모",
    notePlaceholder: "증거 검토 내용과 판정 근거를 기록하세요…",
    accept: "승인",
    reject: "반려",
    needsReview: "추가 검토",
    modelError: "모델 오류",
    record: "판정 기록",
    export: "검증된 번들 내보내기",
    exporting: "내보내는 중…",
    limitations: "데모 적용 범위",
    limitationText: "합성 증거 전용입니다. 생산, 안전, 작업장 출하 검증을 주장하지 않습니다.",
    caseIdentity: "부품 + 리비전 식별",
    caseRevision: "케이스 상태 리비전",
    referenceHash: "기준 이미지 해시",
    inputHash: "검사 이미지 해시",
    configHash: "설정 해시",
    maskHash: "이상 마스크 해시",
    reviewRecord: "사람 검토 기록",
    openCase: "검사 케이스 열기",
    language: "언어",
    processing: "처리 중…",
    safeFailure: "작업이 안전하게 중단되었습니다",
    dismissError: "오류 닫기",
    dismissNotice: "알림 닫기",
    selectCase: "케이스를 선택하거나 새로 만드세요.",
    captured: "증거 번들 검증 완료",
    normalizedDifference: "정규화 픽셀 차이",
    unmapped: "매핑되지 않음",
    notApplicable: "매핑할 이상 없음",
    statusDraft: "초안",
    statusReady: "준비됨",
    statusAnalyzed: "분석됨",
    statusDisposed: "검토됨",
    statusExported: "내보냄",
    statusFailed: "차단됨",
    evaluation: {
      kicker: "사전 등록된 E1 증거",
      title: "합성 강건성 평가",
      summary: "동결된 최신 E1 결과와 출시 게이트를 읽기 전용으로 보여줍니다.",
      boundaryBadge: "합성 데이터 전용 · NOT FIELD_READY",
      boundaryText: "이 결과는 결정론적 합성 fixture만 설명합니다. 실제 카메라, 부품, 작업자, 안전 또는 작업장 출하를 검증하지 않습니다.",
      loadingTitle: "최신 E1 스냅샷을 불러오는 중",
      loadingText: "로컬 API에서 동결 결과, 게이트 증거, 제한된 갤러리를 읽고 있습니다.",
      errorTitle: "평가 증거를 불러올 수 없습니다",
      errorText: "표시 가능한 결과를 수락하지 않았습니다. 기존 검사 기능은 그대로 사용할 수 있습니다.",
      emptyTitle: "게시된 E1 평가가 없습니다",
      emptyText: "이 읽기 전용 화면 밖에서 E1 산출물을 생성·검증한 뒤 새로고침하세요.",
      retry: "다시 읽기",
      refresh: "스냅샷 새로고침",
      latestSnapshot: "최근 수락된 스냅샷",
      verdict: "출시 게이트 판정",
      passMeaning: "이 합성 프로필의 표시된 사전 등록 게이트가 모두 통과했습니다.",
      holdMeaning: "하나 이상의 사전 등록 게이트가 이 합성 프로필을 차단했습니다.",
      profileContract: "데이터셋 프로필",
      activeProfile: "활성",
      selectProfile: "평가 프로필 불러오기",
      miniProfile: "미니",
      fullProfile: "전체",
      cases: "케이스",
      profileCases: "프로필 케이스",
      inferenceCases: "추론 케이스",
      trustCases: "신뢰 경계 케이스",
      runId: "평가 실행",
      generatedAt: "생성 시각",
      baseline: "고정 기준선",
      imageThreshold: "이미지 임계값",
      thresholdSource: "임계값 선택 분할",
      gatesTitle: "PASS / HOLD 게이트",
      gatesHint: "보류 테스트 결과를 보기 전에 임계값을 동결했습니다.",
      noGates: "교정 단계에서 HOLD되어 테스트 게이트를 평가하지 않았습니다. 합성된 0 값은 표시하지 않습니다.",
      gatesTable: "E1 수락 게이트 결과",
      gate: "게이트",
      observed: "관측값",
      required: "요구값",
      evidenceCount: "증거 수",
      status: "상태",
      metricsTitle: "핵심 지표",
      metricsHint: "모든 비율에 분자와 분모를 함께 표시합니다.",
      noMetrics: "교정 단계에서 HOLD되어 테스트 지표를 평가하지 않았습니다. 합성된 0 값은 표시하지 않습니다.",
      undefinedMetric: "이 평가 슬라이스에서는 정의되지 않음",
      confusionTitle: "원시 혼동행렬",
      confusionHint: "보류 이미지 판정을 반올림하지 않은 TP, TN, FP, FN 개수로 표시합니다.",
      confusionTable: "E1 보류 이미지 혼동행렬",
      actualOutcome: "실제 결과",
      predictedAnomaly: "이상 예측",
      predictedNormal: "정상 예측",
      actualAnomaly: "실제 이상",
      actualNormal: "실제 정상",
      truePositive: "참양성 (TP)",
      trueNegative: "참음성 (TN)",
      falsePositive: "거짓양성 (FP)",
      falseNegative: "거짓음성 (FN)",
      totalEvaluated: "전체 평가 수",
      noConfusion: "보류 혼동행렬이 생성되지 않았습니다.",
      distributionTitle: "양성 케이스 Dice / IoU 분포",
      distributionHint: "모든 보류 양성 케이스를 표시하며, 중앙값이 케이스별 증거를 대체하지 않습니다.",
      distributionTable: "E1 양성 케이스 Dice 및 IoU 분포",
      defectType: "결함 유형",
      severity: "심각도",
      dice: "Dice",
      iou: "IoU",
      truthPixels: "정답 픽셀",
      predictedPixels: "예측 픽셀",
      intersectionPixels: "교집합",
      showingDistribution: "전체 표시",
      positiveCases: "개 양성 케이스",
      noDistribution: "보류 양성 케이스 분포가 생성되지 않았습니다.",
      slicesTitle: "평가 슬라이스",
      slicesHint: "슬라이스별 증거로 집계 점수가 하위 그룹 실패를 가리지 못하게 합니다.",
      slicesTable: "평가 슬라이스별 E1 지표 결과",
      slice: "슬라이스",
      sampleCount: "샘플",
      metric: "지표",
      value: "값",
      noSlices: "이 스냅샷에 슬라이스 지표가 없습니다.",
      trustTitle: "신뢰 경계 점검",
      trustHint: "잘못된 입력은 예상 코드를 반환하고 산출물을 하나도 게시하지 않아야 합니다.",
      trustTable: "E1 신뢰 경계 결과",
      caseId: "케이스",
      expectedCode: "예상 코드",
      observedCode: "관측 코드",
      publishedArtifacts: "게시 산출물",
      noTrustCases: "이 스냅샷에 신뢰 경계 케이스가 없습니다.",
      galleryTitle: "오류 탐색기",
      galleryHint: "원본, 마스크, 오버레이, 식별 정보, 해시 증거를 나란히 보여주는 제한된 검토 표본입니다.",
      showingGallery: "표시",
      ofGallery: "/",
      galleryItems: "개 갤러리 항목",
      category: "실패 범주",
      part: "부품 ID",
      cadRevision: "CAD 리비전",
      expectedFeature: "예상 피처",
      predictedFeature: "예측 피처",
      failureReason: "실패 사유",
      notRecorded: "기록 없음",
      assetUnavailable: "게시되지 않음",
      referenceAsset: "정상 기준",
      inspectionAsset: "검사 이미지",
      authoritativeMaskAsset: "정답 마스크",
      predictedMaskAsset: "예측 마스크",
      overlayAsset: "오버레이",
      sourceHashes: "정확한 원본 해시",
      sourceReferenceHash: "기준 SHA-256",
      sourceInspectionHash: "검사 SHA-256",
      sourceAuthoritativeMaskHash: "정답 마스크 SHA-256",
      sourcePredictedMaskHash: "예측 마스크 SHA-256",
      score: "점수",
      galleryThreshold: "잠긴 임계값",
      noGallery: "이 스냅샷에 갤러리 자산이 없습니다.",
      reproductionTitle: "정확한 재현 명령",
      reproductionHint: "저장소 루트에서 다음 명령을 실행하세요. 이 화면은 명령을 실행하지 않습니다.",
      reproductionCommands: "E1 평가 재현 명령",
      exclusionsTitle: "프로토콜 제외 항목",
      limitationsTitle: "적용 범위 제한",
      lineageTitle: "불변 결과 바인딩",
      protocol: "프로토콜",
      dataset: "데이터셋",
      datasetHash: "데이터셋 매니페스트",
      configurationHash: "설정",
      thresholdLock: "임계값 잠금",
      resultHash: "결과",
      commit: "코드 커밋",
      worktree: "작업 트리",
      clean: "깨끗함",
      dirty: "변경 있음 — HOLD 검토 필요",
      gateLabels: {
        mediumHighDefectRecall: "중간/높음 결함 재현율",
        nuisanceOnlyFalsePositiveRate: "교란 전용 오탐률",
        positiveCaseMedianDice: "양성 케이스 Dice 중앙값",
        affectedFeatureMappingAccuracy: "영향 피처 매핑 정확도",
        revisionMismatchPublicationCount: "리비전 불일치 게시 수",
        corruptedEvidencePublicationCount: "손상 증거 게시 수",
        bundleVerifyReimportRate: "번들 검증/재가져오기 비율",
        datasetSplitHashOverlap: "데이터셋 분할 해시 중복",
        sameSeedManifestEquivalence: "동일 시드 매니페스트 동등성",
        v01Regression: "v0.1 회귀",
      },
      metricLabels: {
        imagePrecision: "이미지 정밀도",
        imageRecall: "이미지 재현율",
        maskPrecision: "마스크 정밀도",
        maskRecall: "마스크 재현율",
        abstentionCorrectness: "기권 정확성",
        classificationAccuracy: "분류 정확도",
      },
      sliceLabels: {
        recallBySeverity: "심각도별 재현율",
        recallByDefectType: "결함 유형별 재현율",
        nuisanceFalsePositiveRate: "교란 오탐률",
        classificationByRevision: "리비전별 분류 정확도",
        classificationByView: "뷰별 분류 정확도",
      },
    },
    footerTarget: "DEMO_READY 목표 · 합성 fixture",
    footerContract: "증거 계약 v1.0.0",
    footerBoundary: "생산 검증되지 않음",
  },
} as const;

export type Copy = (typeof copy)["en"];

export function getCopy(locale: Locale): Copy {
  return copy[locale] as Copy;
}
